name: '⚓ Quay.io Login ᵛ³'
description: 'GitHub Action to login against a Quay.io'

inputs:
  registry:
    type: string
    default: 'quay.io'
    description: 'Server address of Quay.io, If not set then will default to Docker Hub'
    required: false
  username:
    type: string
    default: null
    description: 'Username used to log against the Quay.io'
    required: false
  password:
    type: string
    default: null
    description: 'Password or Quay.io Robot Token used to log against the Quay.io'
    required: false
  ecr:
    type: string
    default: 'auto'
    description: 'Specifies whether the given registry is ECR (auto, true or false)'
    required: false
  logout:
    type: boolean
    default: true
    description: 'Log out from the Quay.io at the end of a job'
    required: false
runs:
  using: "composite"
  steps:
    - name: 🧩 Quay.io Login ᵛ³
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        ecr: ${{ inputs.ecr }}
        logout: ${{ inputs.logout }}
