variable "action" {
  type        = string
  default     = "lambda:InvokeFunction"
  description = "The AWS Lambda action you want to allow in this statement."
  validation {
    condition     = var.action != null
    error_message = "Error: action must not null."
  }
  sensitive = false
}

variable "function_name" {
  type        = string
  default     = "generic"
  description = "Name of the Lambda function whose resource policy you are updating."
  validation {
    condition     = var.function_name != null && 0 <= length(var.function_name) && length(var.function_name) <= 64
    error_message = "Error: function_name length must be in between 0 and 64 only."
  }
  sensitive = false
}

variable "principal" {
  type        = string
  default     = "apigateway.amazonaws.com"
  description = "The principal who is getting this permission."
  validation {
    condition     = var.principal != null
    error_message = "Error: principal must not null."
  }
  sensitive = false
}

variable "statement_id" {
  type        = string
  default     = "AllowExecutionFromAPIGateway"
  description = "A unique statement identifier. By default generated by Terraform."
  validation {
    condition     = var.statement_id != null
    error_message = "Error: statement_id must not null."
  }
  sensitive = false
}

variable "source_arn" {
  type        = string
  default     = "AllowExecutionFromAPIGateway"
  description = "A unique statement identifier. By default generated by Terraform."
  validation {
    condition     = var.source_arn != null
    error_message = "Error: source_arn must not null."
  }
  sensitive = false
}