name: '🐳 Docker Setup QEMU'
description: 'Install QEMU static binaries'

on:
  workflow_call:
    inputs:
      cache-image:
        type: boolean
        default: true
        description: 'Cache binfmt image to GitHub Actions cache backend'
        required: false
      image:
        type: string
        default: 'docker.io/tonistiigi/binfmt:latest'
        description: 'QEMU static binaries Docker image (e.g. tonistiigi/binfmt:latest)'
        required: false
      platforms:
        type: string
        default: 'all'
        description: 'Platforms to install (e.g. arm64,riscv64,arm)'
        required: false
    outputs:
      platforms:
        description: 'Available platforms (comma separated)'
        value: ${{ jobs.job-setup-qemu-action.outputs.platforms }}

jobs:
  job-job-setup-qemu-action:
    name: Job - Docker Setup QEMU
    runs-on: ubuntu-latest
    steps:
      - name: Step - Docker Setup QEMU
        id: step-setup-qemu-action
        uses: docker/setup-qemu-action@v3
        with:
          cache-image: ${{ inputs.cache-image }}
          image: ${{ inputs.image }}
          platforms: ${{ inputs.platforms }}
    outputs:
      sock: ${{ steps.step-setup-docker-action.outputs.sock }}
