name: '🐙 GHCR Login ᵛ³'
description: 'GitHub Action to login against a GitHub Container Registry'

inputs:
  registry:
    type: string
    default: 'ghcr.io'
    description: 'Server address of GitHub Container Registry. If not set then will default to Docker Hub'
    required: false
  username:
    type: string
    default: null
    description: 'Username used to log against the GitHub'
    required: false
  password:
    type: string
    default: null
    description: 'Password or PAT (Personal Access Token) used to log against the GitHub Container Registry'
    required: false
  ecr:
    type: string
    default: 'auto'
    description: 'Specifies whether the given registry is ECR (auto, true or false)'
    required: false
  logout:
    type: boolean
    default: true
    description: 'Log out from the GitHub Container Registry at the end of a job'
    required: false
runs:
  using: "composite"
  steps:
    - name: 🧩 GHCR Login ᵛ³
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        ecr: ${{ inputs.ecr }}
        logout: ${{ inputs.logout }}
