name: Docker Login Action
description: Logs in to DockerHub
inputs:
  username:
    required: true
  password:
    required: true
runs:
  using: "composite"
  steps:
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

