name: Docker Login Action
description: Logs in to DockerHub
inputs:
  username:
    type: string
    required: true
  password:
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}     # ✅ Correct
        password: ${{ inputs.password }}     # ✅ Correct
