FROM scratch AS go1.21.0

LABEL \
  # Authors or maintainers of the image.
  org.opencontainers.image.authors="Balaji Pothula <balan.pothula@gmail.com>" \
  # Image reference of the image.
  org.opencontainers.image.base.name="scratch" \
  # Title or name for the image.
  org.opencontainers.image.title="go:1.21.0" \
  # Version of the packaged software.
  org.opencontainers.image.version="1.21.0" \
  # Description or summary of the image.
  org.opencontainers.image.description="GO 1.21.0 - Programming language" \
  # Name of the distributing entity, organization or individual.
  org.opencontainers.image.vendor="Blitz Systems Pvt. Ltd. <https://blitzsystems.in>"

# Set working directory
WORKDIR /webapp  

# Mount point for WebApp go lang file.
VOLUME ["/webapp"]

# Expose port 80 for incoming HTTP traffic.
# Container will listen on port 80 using TCP.
EXPOSE 80/tcp

# Set the entrypoint to start main with go fiber v2.
ENTRYPOINT ["/webapp/main"]
