app             = "go-fiber-app"
primary_region  = "fra"
kill_signal     = "SIGINT"
kill_timeout    = 5
swap_size_mb    = 256
console_command = "/bin/sh"

[experimental]
  auto_rollback   = true

[deploy]
  strategy        = "rolling"
  max_unavailable = 1
  wait_timeout    = "9m59s"

[build]
##image      = "docker.io/balajipothula/go:1.21.0"
  image      = "docker.io/balajipothula/dropbear:2025.88-r1"
##dockerfile = "./Dockerfile.go1.21.0"
##context    = "."

[[mounts]]
  source                     = "go_fiber_volume"
  destination                = "/gofiber"
  name                       = "go-fiber-volume"
  region                     = "fra"
  initial_size               = "1GB"
  snapshot_retention         = 1
  encrypted                  = false
  shared                     = true
  auto_extend_size_threshold = 70
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit     = "3GB"

[http_service]
  internal_port        = 3000
  force_https          = true
  auto_stop_machines   = "stop"
  auto_start_machines  = true
  min_machines_running = 0
  concurrency          = { type = "connections", soft_limit = 20, hard_limit = 25 }
  [http_service.http_options]
    idle_timeout = 600
  [http_service.http_options.response]
    pristine = true

[[vm]]
  size     = "shared-cpu-1x"
  memory   = "256mb"
  cpu_kind = "shared"
  cpus     = 1

[[restart]]
  policy    = "never"
  retries   = 10
  processes = ["app"]
