name: 'ðŸ™ Checkout áµ›Â³'
description: 'Checkout a Git repository at a particular version.'

inputs:
  repository:
    type: string
    default: ${{ github.repository }}
    description: 'Repository name with owner. For example, actions/checkout'
    required: false
  ref:
    type: string
    description: 'Git ref (branch, tag, or SHA) to checkout.'
    required: false
  token:
    type: string
    default: ${{ github.token }}
    description: 'GitHub token or PAT (Personal access token) for authenticated Git access.'
    required: false
  ssh-key:
    type: string
    description: 'SSH key for private repository access.'
    required: false
  ssh-known-hosts:
    type: string
    description: 'Additional known hosts for SSH verification.'
    required: false
  ssh-strict:
    type: boolean
    default: true
    description: 'Enable strict SSH host key checking.'
    required: false
  persist-credentials:
    type: boolean
    default: true
    description: 'Whether to configure the token or SSH key with the local git config.'
    required: false
  path:
    type: string
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository.'
    required: false
  clean:
    type: boolean
    default: true
    description: 'Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching.'
    required: false
  sparse-checkout:
    type: string
    default: null
    description: Sparse checkout patterns (newline-separated).
    required: false
  sparse-checkout-cone-mode:
    type: boolean
    default: true
    description: 'Specifies whether to use cone-mode when doing a sparse checkout.'
    required: false
  fetch-depth:
    type: number
    default: 1
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags.'
    required: false
  fetch-tags:
    type: boolean
    default: false
    description: 'Whether to fetch tags, even if fetch-depth > 0.'
    required: false
  lfs:
    type: boolean
    default: false
    description: 'Whether to download Git-LFS files.'
    required: false
  submodules:
    type: string
    default: false
    description: 'Whether to checkout submodules: `true` to checkout submodules or `recursive` to recursively checkout submodules.'
    required: false
  set-safe-directory:
    type: boolean
    default: true
    description: 'Add repository path as safe.directory for Git global config by running `git config --global --add safe.directory <path>`'
    required: false
  github-server-url:
    type: string
    description: 'The base URL for the GitHub instance that you are trying to clone from (e.g., https://github.com).'
    required: false

runs:
  using: "composite"
  steps:
    - name: ðŸ§© Checkout áµ›Â³
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
        ssh-key: ${{ inputs.ssh-key }}
        ssh-known-hosts: ${{ inputs.ssh-known-hosts }}
        ssh-strict: ${{ inputs.ssh-strict }}
        persist-credentials: ${{ inputs.persist-credentials }}
        path: ${{ inputs.path }}
        clean: ${{ inputs.clean }}
        sparse-checkout: ${{ inputs.sparse-checkout }}
        sparse-checkout-cone-mode: ${{ inputs.sparse-checkout-cone-mode }}
        fetch-depth: ${{ inputs.fetch-depth }}
        fetch-tags: ${{ inputs.fetch-tags }}
        lfs: ${{ inputs.lfs }}
        submodules: ${{ inputs.submodules }}
        set-safe-directory: ${{ inputs.set-safe-directory }}
        github-server-url: ${{ inputs.github-server-url }}
