name: '☁️ AWS Public ECR Login ᵛ³'
description: 'GitHub Action to login against a AWS'

inputs:
  registry:
    type: string
    default: 'public.ecr.aws'
    description: 'Server address of AWS Public ECR. If not set then will default to Docker Hub'
    required: false
  username:
    type: string
    default: null
    description: 'Username used to log against the AWS'
    required: false
  password:
    type: string
    default: null
    description: 'Password or PAT (Personal Access Token) used to log against the AWS'
    required: false
  ecr:
    type: string
    default: 'auto'
    description: 'Specifies whether the given registry is ECR (auto, true or false)'
    required: false
  logout:
    type: boolean
    default: true
    description: 'Log out from the AWS at the end of a job'
    required: false
runs:
  using: "composite"
  steps:
    - name: 🧩 AWS Public ECR Login ᵛ³
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        ecr: ${{ inputs.ecr }}
        logout: ${{ inputs.logout }}
