name: '📤 Upload a Build Artifact ᵛ⁴'
description: 'Upload a build artifact that can be used by subsequent workflow steps'

on:
  workflow_call:
    inputs:
      name:
        type: string
        default: 'artifact'
        description: 'Artifact name'
        required: false
      path:
        type: string
        default: null
        description: 'A file, directory or wildcard pattern that describes what to upload'
        required: true
      if-no-files-found:
        type: string
        default: 'warn'
        description: >
          The desired behavior if no files are found using the provided path.
          Available Options:
            warn: Output a warning but do not fail the action
            error: Fail the action with an error message
            ignore: Do not output any warnings or errors, the action does not fail
        required: false
      retention-days:
        type: number
        default: 0
        description: >
          Duration after which artifact will expire in days.
          Available Options:
            0 means using default retention.
            Minimum 1 day.
            Maximum 90 days unless changed from the repository settings page.
        required: false
      compression-level:
        type: number
        default: 6
        description: >
          The level of compression for Zlib to be applied to the artifact archive.
          The value can range from 0 to 9:
            0: No compression
            1: Best speed
            6: Default compression (same as GNU Gzip)
            9: Best compression
        required: false
      overwrite:
        type: boolean
        default: false
        description: >
          If true, an artifact with a matching name will be deleted before a new one is uploaded.
          If false, the action will fail if an artifact for the given name already exists.
        required: false
      include-hidden-files:
        type: boolean
        default: false
        description: >
          If true, hidden files will be included in the artifact.
          If false, hidden files will be excluded from the artifact.
        required: false
    outputs:
      artifact-id:
        value: ${{ jobs.job_actions_upload-artifact_v4.outputs.artifact-id }}
        description: 'A unique identifier for the artifact that was just uploaded. Empty if the artifact upload failed. This ID can be used as input to other APIs to download.'
      artifact-url:
        value: ${{ jobs.job_actions_upload-artifact_v4.outputs.artifact-url }}
        description: 'A download URL for the artifact that was just uploaded. Empty if the artifact upload failed. It only works for requests Authenticated with GitHub.'
      artifact-digest:
        value: ${{ jobs.job_actions_upload-artifact_v4.outputs.artifact-digest }}
        description: 'SHA-256 digest for the artifact that was just uploaded. Empty if the artifact upload failed.'

jobs:
  job_actions_upload-artifact_v4:
    name: 🧩 Upload a Build Artifact ᵛ⁴
    runs-on: ubuntu-22.04
    environment: ${{ github.ref }}
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Step - Upload a Build Artifact ᵛ⁴
        id: step_actions_upload-artifact_v4
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.path }}
          if-no-files-found: ${{ inputs.if-no-files-found }}
          retention-days: ${{ inputs.retention-days }}
          compression-level: ${{ inputs.compression-level }}
          overwrite: ${{ inputs.overwrite }}
          include-hidden-files: ${{ inputs.include-hidden-files }}
    outputs:
      artifact-id: ${{ steps.step_actions_upload-artifact_v4.outputs.artifact-id }}
      artifact-url: ${{ steps.step_actions_upload-artifact_v4.outputs.artifact-url }}
      artifact-digest: ${{ steps.step_actions_upload-artifact_v4.outputs.artifact-digest }}
