name: '🤖 CI • Build • Push • GO Artifacts'
description: 'Continuous integration action to build and push GO web application binary artifacts.'  

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: 'dev'
        description: 'Select deployment environment'
        options: ['dev', 'qa', 'prod']
        required: true
      go_filename:
        type: string
        default: 'main.go'
        description: 'Enter GO filename'
        required: true

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.0'
      - name: Initialize Go Module 📦
        working-directory: ./go
        run: |
          if [ ! -f "go.mod" ]; then
            GO_MOD_PATH="github.com/${{ github.repository }}/go"
            go mod init "$GO_MOD_PATH"
          fi
          go get github.com/gofiber/fiber/v2
          go mod tidy

      - name: Build binary
        working-directory: ./go
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main main.go

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
