name: '🤖 CI • Build • Push • GO Artifacts'
description: 'Continuous integration action to build and push GO web application binary artifacts.'  

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: 'dev'
        description: 'Select deployment environment'
        options: ['dev', 'qa', 'prod']
        required: true
      go_filename:
        type: string
        default: 'main.go'
        description: 'Enter GO filename'
        required: true

permissions:
  contents: write

jobs:
  job_actions_setup-go_v5:
    name: 🖱️ Setup Go Environment ᵛ⁵
    uses: ./.github/workflows/actions_setup-go_v5.yml
    with:
      go-version: '1.21.0'
      cache-dependency-path: go/go.sum
  job_init_go_module:
    name: Job - Init Go Module
    needs: [job_actions_setup-go_v5]
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Step - Checkout
        uses: actions/checkout@v4
      - name: Step - Init Go Modules
        working-directory: go
        run: |
          if [ ! -f "go.mod" ]; then
            GO_MOD_PATH="github.com/${{ github.repository }}/go"
            go mod init "$GO_MOD_PATH"
          fi
          go get github.com/gofiber/fiber/v2
          go mod tidy