name: '🤖 CI • Build • Push • GO Artifacts'
description: 'Continuous integration action to build and push GO web application binary artifacts.'  

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: 'dev'
        description: 'Select deployment environment'
        options: ['dev', 'qa', 'prod']
        required: true
      go_filename:
        type: string
        default: 'main.go'
        description: 'Enter GO filename'
        required: true

permissions:
  contents: write

jobs:
  job_get_utc-time-now:
    name: 🕒 Get UTC Time Now
    runs-on: ubuntu-22.04
    steps:
      - name: Step - Get UTC Time Now
        id: step_get_utc-time-now
        run: echo "utc-time-now=$(date -u +'%Y%m%dT%H%M%SZ')" >> "$GITHUB_OUTPUT"
    outputs:
      utc-time-now: ${{ steps.step_get_utc-time-now.outputs.utc-time-now }}
  job_actions_setup-go_v5:
    name: 🐹 Setup Go Environment ᵛ⁵
    runs-on: ubuntu-22.04
    steps:
      - name: Step - Checkout
        uses: actions/checkout@v3
        with:
          repository: '${{ github.repository }}'
          token: '${{ github.token }}'
      - name: Step - Setup Go Environment ᵛ⁵
        uses: ./.github/actions/actions_setup-go_v5
        with:
          go-version: '1.21.0'
          cache-dependency-path: go
      - name: Step - Init Go Modules
        working-directory: go
        run: |
          if [ ! -f "go.mod" ]; then
            GO_MOD_PATH="github.com/${{ github.repository }}/go"
            go mod init "$GO_MOD_PATH"
          fi
          go get github.com/gofiber/fiber/v2
          go mod tidy
