name: '🤖 CI • Build • Push • GO Artifacts'
description: 'Continuous integration action to build and push GO web application binary artifacts.'  

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: 'dev'
        description: 'Select deployment environment'
        options: ['dev', 'qa', 'prod']
        required: true
      go_filename:
        type: string
        default: 'main.go'
        description: 'Enter GO filename'
        required: true

permissions:
  contents: write

jobs:
  job_actions_setup-go_v5:
    name: Step - Setup Go Environment ᵛ⁵
    uses: ./.github/workflows/actions_setup-go_v5.yml
    with:
      go-version: '1.21.0'
      go-version-file: 'github.com/${{ github.repository }}/go'
      cache-dependency-path: go/go.sum
