name: 🚀 WebApp Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: 'dev'
        description: 'Please select deployment environment'
        options: [dev, qa, prod]
        required: true
      run_terraform:
        type: boolean
        default: false
        description: 'Run Terraform Infra Provision?'
        required: true
      run_liquibase:
        type: boolean
        default: false
        description: 'Run Liquibase Update Action?'
        required: true
      run_docker:
        type: boolean
        default: false
        description: 'Run Docker Build and Push?'
        required: true

jobs:
  docker:
    uses: ./.github/workflows/build-docker.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

