name: 🚀 WebApp Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: 'dev'
        description: 'Please select deployment environment'
        options: [dev, qa, prod]
        required: true
      setup_qemu_action_v3:
        type: boolean
        default: false
        description: 'Run Setup QEMU Action v3'

jobs: 
  setup-qemu:
    name: Job - Docker Setup QEMU
    if: ${{ inputs.setup_qemu_action_v3 == true }}
    uses: ./.github/workflows/docker/setup-qemu-action-v3.yml
    with:
      cache-image: true
