name: 🚀 WebApp Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: 'dev'
        description: 'Please select deployment environment'
        options: [dev, qa, prod]
        required: true
      docker_setup_qemu_action_v3:
        type: boolean
        default: false
        description: '🐳 Docker Setup QEMU ᵛ³'
      docker_setup_buildx_action_v3:
        type: boolean
        default: false
        description: '🐳 Docker Setup Buildx ᵛ³'
      docker_login_action_v3:
        type: boolean
        default: false
        description: '🐳 Docker Login ᵛ³'
      ghcr_login_action_v3:
        type: boolean
        default: false
        description: '🐙 GHCR Login ᵛ³'
      gitlab_login_action_v3:
        type: boolean
        default: false
        description: '🦊 GitLab Login ᵛ³'
      aws_public_ecr_login_action_v3:
        type: boolean
        default: false
        description: '☁️ AWS Public ECR Login ᵛ³'
      aws_ecr_login_action_v3:
        type: boolean
        default: false
        description: '☁️ AWS ECR Login ᵛ³'
      quay_io_login_action_v3:
        type: boolean
        default: false
        description: '⚓ Quay.io Login ᵛ³'
      digital-ocean_login_action_v3:
        type: boolean
        default: false
        description: '💧 DigitalOcean Login ᵛ³'

jobs: 
  job_docker_setup-qemu-action_v3:
    name: 🖱️ Docker Setup QEMU
    if: ${{ inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/docker__setup-qemu-action__v3.yml
  job_docker_setup-buildx-action_v3:
    name: 🖱️ Docker Setup Buildx
    needs: job_docker_setup-qemu-action_v3
    if: ${{ inputs.docker_setup_buildx_action_v3 && inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/docker__setup-buildx-action__v3.yml
  job_docker_login-action_v3:
    name: 🖱️ Docker Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.docker_login_action_v3 && inputs.docker_setup_buildx_action_v3 && inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/docker__login-action__v3.yml
    with:
      username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  job_ghcr_login-action_v3:
    name: 🖱️ GHCR Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.ghcr_login_action_v3 && inputs.docker_setup_buildx_action_v3 && inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/ghcr__login-action__v3.yml
    with:
      username: ${{ github.actor }}
    secrets:
      TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
  job_gitlab_login-action_v3:
    name: 🖱️ GitLab Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.gitlab_login_action_v3 && inputs.docker_setup_buildx_action_v3 && inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/gitlab__login-action__v3.yml
    with:
      username: ${{ vars.GITLAB_USERNAME }}
    secrets:
      GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
  job_aws-public-ecr_login-action_v3:
    name: 🖱️ AWS Public ECR Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.aws_public_ecr_login_action_v3 && inputs.docker_setup_buildx_action_v3 && inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/aws-public-ecr__login-action__v3.yml
    with:
      AWS_PUBLIC_ECR_REGION: 'us-east-1'
      username: ${{ vars.AWS_ACCESS_KEY_ID }}
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  job_aws-ecr_login-action_v3:
    name: 🖱️ AWS ECR Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.aws_ecr_login_action_v3 && inputs.docker_setup_buildx_action_v3 && inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/aws-ecr__login-action__v3.yml
    with:
      registry: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_ECR_REGION }}.amazonaws.com
      username: ${{ vars.AWS_ACCESS_KEY_ID }}
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  job_quay-io_login-action_v3:
    name: 🖱️ Quay.io Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.quay_io_login_action_v3 && inputs.docker_setup_buildx_action_v3 && inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/quay-io__login-action__v3.yml
    with:
      username: ${{ vars.QUAY_USERNAME }}
    secrets:
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
  job_digital-ocean_login-action_v3:
    name: 🖱️ DigitalOcean Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.digital-ocean_login_action_v3 && inputs.docker_setup_buildx_action_v3 && inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/digital-ocean__login-action__v3.yml
    with:
      username: ${{ vars.DIGITALOCEAN_USERNAME }}
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
