name: 🚀 WebApp Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: 'dev'
        description: 'Please select deployment environment'
        options: [dev, qa, prod]
        required: true
      setup_qemu_action_v3:
        type: boolean
        default: false
        description: 'Run Docker Setup QEMU'
      setup_buildx_action_v3:
        type: boolean
        default: false
        description: 'Run Docker Setup Buildx'

jobs: 
  job-setup-qemu-action:
    name: Job - Docker Setup QEMU
    if: ${{ inputs.setup_qemu_action_v3 == true }}
    uses: ./.github/workflows/docker__setup-qemu-action__v3.yml
  job-setup-buildx-action:
    name: Job - Docker Setup Buildx
    if: ${{ inputs.setup_buildx_action_v3 == true && inputs.setup_qemu_action_v3 == true }}
    needs: job-setup-qemu-action
    uses: ./.github/workflows/docker__setup-buildx-action__v3.yml
