name: 🚀 WebApp Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: 'dev'
        description: 'Please select deployment environment'
        options: [dev, qa, prod]
        required: true
      run_terraform:
        type: boolean
        default: false
        description: 'Run Terraform Infra Provision'
      run_liquibase:
        type: boolean
        default: false
        description: 'Run Liquibase Update Action'
      run_docker:
        type: boolean
        default: false
        description: 'Run Docker Build and Push'

jobs:
  terraform:
    if: ${{ inputs.run_terraform == false }}
    uses: ./.github/workflows/terraform-deploy.yml
    secrets:
      WEBAPP_DB_NAME: ${{ secrets.WEBAPP_DB_NAME }}
      WEBAPP_DB_MASTER_USERNAME: ${{ secrets.WEBAPP_DB_MASTER_USERNAME }}
      WEBAPP_DB_MASTER_PASSWORD: ${{ secrets.WEBAPP_DB_MASTER_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  docker:
    if: ${{ inputs.run_terraform == false }}
    uses: ./.github/workflows/build-docker.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
