name: 🚀 WebApp Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: 'dev'
        description: 'Please select deployment environment'
        options: [dev, qa, prod]
        required: true
      docker_setup_qemu_action_v3:
        type: boolean
        default: false
        description: 'Run Docker Setup QEMU'
      docker_setup_buildx_action_v3:
        type: boolean
        default: false
        description: 'Run Docker Setup Buildx'
      docker_login_action_v3:
        type: boolean
        default: false
        description: 'Run Docker Login Action'
      gcr_login_action_v3:
        type: boolean
        default: false
        description: 'Run GCR Login Action'
      gitlab_login_action_v3:
        type: boolean
        default: false
        description: 'Run GitLab Login Action'

jobs: 
  job_docker_setup-qemu-action_v3:
    name: Job - Docker Setup QEMU
    if: ${{ inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/docker__setup-qemu-action__v3.yml
  job_docker_setup-buildx-action_v3:
    name: Job - Docker Setup Buildx
    needs: job_docker_setup-qemu-action_v3
    if: ${{ inputs.docker_setup_buildx_action_v3 && inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/docker__setup-buildx-action__v3.yml
  job-docker-login-action:
    name: Job - Docker Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.docker_login_action_v3 && inputs.docker_setup_buildx_action_v3 && inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/docker__login-action__v3.yml
    with:
      username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  job-gcr-login-action:
    name: Job - GCR Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.gcr_login_action_v3 && inputs.docker_setup_buildx_action_v3 && inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/gcr__login-action__v3.yml
    with:
      username: ${{ github.actor }}
    secrets:
      TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
  job-gitlab-login-action:
    name: Job - GitLab Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.gitlab_login_action_v3 && inputs.docker_setup_buildx_action_v3 && inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/gitlab__login-action__v3.yml
    with:
      username: ${{ vars.GITLAB_USERNAME }}
    secrets:
      GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
