name: 🚀 WebApp Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: 'dev'
        description: 'Please select deployment environment'
        options: [dev, qa, prod]
        required: true
      docker_setup_qemu_action_v3:
        type: boolean
        default: false
        description: '🐳 Docker Setup QEMU'
      docker_setup_buildx_action_v3:
        type: boolean
        default: false
        description: '🐳 Docker Setup Buildx'
      docker_login_action_v3:
        type: boolean
        default: false
        description: '🐳 Docker Login'
      ghcr_login_action_v3:
        type: boolean
        default: false
        description: '🐙 GHCR Login'
      gitlab_login_action_v3:
        type: boolean
        default: false
        description: '🦊 GitLab Login'
      aws_public_ecr_login_action_v3:
        type: boolean
        default: false
        description: '☁️ AWS Public ECR Login'

jobs: 
  job_docker_setup-qemu-action_v3:
    name: Job - Docker Setup QEMU
    if: ${{ inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/docker__setup-qemu-action__v3.yml
  job_docker_setup-buildx-action_v3:
    name: Job - Docker Setup Buildx
    needs: job_docker_setup-qemu-action_v3
    if: ${{ inputs.docker_setup_buildx_action_v3 && inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/docker__setup-buildx-action__v3.yml
  job-docker-login-action:
    name: Job - Docker Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.docker_login_action_v3 && inputs.docker_setup_buildx_action_v3 && inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/docker__login-action__v3.yml
    with:
      username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  job-ghcr-login-action:
    name: Job - GHCR Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.ghcr_login_action_v3 && inputs.docker_setup_buildx_action_v3 && inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/ghcr__login-action__v3.yml
    with:
      username: ${{ github.actor }}
    secrets:
      TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
  job-gitlab-login-action:
    name: Job - GitLab Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.gitlab_login_action_v3 && inputs.docker_setup_buildx_action_v3 && inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/gitlab__login-action__v3.yml
    with:
      username: ${{ vars.GITLAB_USERNAME }}
    secrets:
      GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
  job-aws-public-ecr-login-action:
    name: Job - AWS Public ECR Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.aws_public_ecr_login_action_v3 && inputs.docker_setup_buildx_action_v3 && inputs.docker_setup_qemu_action_v3 }}
    uses: ./.github/workflows/aws-public-ecr__login-action__v3.yml
    with:
      AWS_ECR_REGION: 'eu-central-1'
      registry: ''
      username: ${{ vars.AWS_ACCESS_KEY_ID }}
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
