name: '🚀 WebApp Deployment'
description: 'Deploying Python FastAPI WebApplication'

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: 'dev'
        description: 'Please select deployment environment'
        options: [dev, qa, prod]
        required: true
      docker_setup-qemu-action_v3:
        type: boolean
        default: false
        description: '🐳 Docker Setup QEMU ᵛ³'
      docker_setup-buildx-action_v3:
        type: boolean
        default: false
        description: '🐳 Docker Setup Buildx ᵛ³'
      docker_login-action_v3:
        type: boolean
        default: false
        description: '🐳 Docker Login ᵛ³'
      ghcr_login-action_v3:
        type: boolean
        default: false
        description: '🐙 GHCR Login ᵛ³'
      gitlab_login-action_v3:
        type: boolean
        default: false
        description: '🦊 GitLab Login ᵛ³'
      aws-public-ecr_login-action_v3:
        type: boolean
        default: false
        description: '☁️ AWS Public ECR Login ᵛ³'
      aws-ecr_login-action_v3:
        type: boolean
        default: false
        description: '☁️ AWS ECR Login ᵛ³'
      quay-io_login-action_v3:
        type: boolean
        default: false
        description: '⚓ Quay.io Login ᵛ³'
      digital-ocean_login-action_v3:
        type: boolean
        default: false
        description: '💧 DigitalOcean Login ᵛ³'
      docker_build-push-action_v6:
        type: boolean
        default: false
        description: '🐳 Docker Build & Push ᵛ⁶'

jobs:
  job_get_utc-time-now:
    name: 🕒 Get UTC Time Now
    runs-on: ubuntu-22.04
    steps:
      - name: Step - Get UTC Time Now
        id: step_get_utc-time-now
        run: echo "utc-time-now=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"
    outputs:
      utc-time-now: ${{ steps.step_get_utc-time-now.outputs.utc-time-now }}
  job_docker_setup-qemu-action_v3:
    name: 🖱️ Docker Setup QEMU
    if: ${{ inputs.docker_setup-qemu-action_v3 }}
    uses: ./.github/workflows/docker__setup-qemu-action__v3.yml
  job_docker_setup-buildx-action_v3:
    name: 🖱️ Docker Setup Buildx
    needs: job_docker_setup-qemu-action_v3
    if: ${{ inputs.docker_setup-qemu-action_v3 && inputs.docker_setup-buildx-action_v3 }}
    uses: ./.github/workflows/docker__setup-buildx-action__v3.yml
  job_docker_login-action_v3:
    name: 🖱️ Docker Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.docker_setup-qemu-action_v3 && inputs.docker_setup-buildx-action_v3 && inputs.docker_login-action_v3}}
    uses: ./.github/workflows/docker__login-action__v3.yml
    with:
      username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  job_ghcr_login-action_v3:
    name: 🖱️ GHCR Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.docker_setup-qemu-action_v3 && inputs.docker_setup-buildx-action_v3 && inputs.ghcr_login-action_v3 }}
    uses: ./.github/workflows/ghcr__login-action__v3.yml
    with:
      username: ${{ github.actor }}
    secrets:
      TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
  job_gitlab_login-action_v3:
    name: 🖱️ GitLab Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.docker_setup-qemu-action_v3 && inputs.docker_setup-buildx-action_v3 && inputs.gitlab_login-action_v3 }}
    uses: ./.github/workflows/gitlab__login-action__v3.yml
    with:
      username: ${{ vars.GITLAB_USERNAME }}
    secrets:
      GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
  job_aws-public-ecr_login-action_v3:
    name: 🖱️ AWS Public ECR Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.docker_setup-qemu-action_v3 && inputs.docker_setup-buildx-action_v3 && inputs.aws-public-ecr_login-action_v3 }}
    uses: ./.github/workflows/aws-public-ecr__login-action__v3.yml
    with:
      AWS_PUBLIC_ECR_REGION: 'us-east-1'
      username: ${{ vars.AWS_ACCESS_KEY_ID }}
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  job_aws-ecr_login-action_v3:
    name: 🖱️ AWS ECR Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.docker_setup-qemu-action_v3 && inputs.docker_setup-buildx-action_v3 && inputs.aws-ecr_login-action_v3 }}
    uses: ./.github/workflows/aws-ecr__login-action__v3.yml
    with:
      registry: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_ECR_REGION }}.amazonaws.com
      username: ${{ vars.AWS_ACCESS_KEY_ID }}
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  job_quay-io_login-action_v3:
    name: 🖱️ Quay.io Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.docker_setup-qemu-action_v3 && inputs.docker_setup-buildx-action_v3 && inputs.quay-io_login-action_v3 }}
    uses: ./.github/workflows/quay-io__login-action__v3.yml
    with:
      username: ${{ vars.QUAY_USERNAME }}
    secrets:
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
  job_digital-ocean_login-action_v3:
    name: 🖱️ DigitalOcean Login
    needs: job_docker_setup-buildx-action_v3
    if: ${{ inputs.docker_setup-qemu-action_v3 && inputs.docker_setup-buildx-action_v3 && inputs.digital-ocean_login-action_v3 }}
    uses: ./.github/workflows/digital-ocean__login-action__v3.yml
    with:
      username: ${{ vars.DIGITALOCEAN_USERNAME }}
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  job_docker_build-push-action_v6:
    name: 🖱️ DigitalOcean Login
    needs: [job_get_utc-time-now, job_docker_login-action_v3]
    if: ${{ inputs.docker_setup-qemu-action_v3 && inputs.docker_setup-buildx-action_v3 && inputs.docker_login-action_v3 && inputs.docker_build-push-action_v6 }}
    uses: ./.github/workflows/docker__build-push-action__v6.yml
    with:
      file: './docker/Dockerfile.nginx1.28.0'
      labels: |
        org.opencontainers.image.created='${{ needs.job_get_utc-time-now.outputs.utc-time-now }}'
      platforms: linux/amd64
      push: true
      tags: balajipothula/nginx:1.28.0
