name: '🐳 Docker Setup Docker'
description: 'Set up Docker for use in GitHub Actions by downloading and installing a version of Docker CE'

on:
  workflow_call:
    inputs:
      channel:
        type: string
        default: 'stable'
        description: 'Docker CE channel (allowed: `stable`, `edge`, or `test`)'
        required: false
      context:
        type: string
        default: 'setup-docker-action'
        description: 'Docker context name'
        required: false
      daemon-config:
        type: string
        description: 'Docker daemon JSON configuration'
        required: false
      rootless:
        type: boolean
        default: false
        description: 'Enable Docker rootless mode'
        required: false
      set-host:
        type: boolean
        default: false
        description: 'Set DOCKER_HOST environment variable to Docker socket path'
        required: false
      tcp-port:
        type: number
        description: 'TCP port to expose the Docker API locally'
        required: false
      version:
        type: string
        default: 'latest'
        description: 'Docker CE version (e.g., v24.0.9)'
        required: false
    outputs:
      sock:
        value: ${{ jobs.job-setup-docker-action.outputs.sock }}
        description: 'Docker socket path'
      tcp:
        value: ${{ jobs.job-setup-docker-action.outputs.tcp }}
        description: 'Docker TCP address if tcp-port is set'

jobs:
  job-setup-docker-action:
    name: Job - Setup Docker Action
    runs-on: ubuntu-22.04
    environment: dev
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Step - Setup Docker Action
        id: step-setup-docker-action
        uses: docker/setup-docker-action@v4
        with:
          channel: ${{ inputs.channel }}
          context: ${{ inputs.context }}
          daemon-config: ${{ inputs.daemon-config }}
          rootless: ${{ inputs.rootless }}
          set-host: ${{ inputs.set-host }}
          tcp-port: ${{ inputs.tcp-port }}
          version: ${{ inputs.version }}
    outputs:
      sock: ${{ steps.step-setup-docker-action.outputs.sock }}
      tcp: ${{ steps.step-setup-docker-action.outputs.tcp }}
