name: '๐ณ Docker Setup Compose แตยน'
description: 'Set up Docker Compose'

on:
  workflow_call:
    inputs:
      version:
        type: string
        default: null
        description: 'Compose version. (eg. v2.32.4)'
        required: false
      cache-binary:
        type: boolean
        default: true
        description: 'Cache compose binary to GitHub Actions cache backend'
        required: false

jobs:
  job_docker_setup-compose-action_v1:
    name: ๐งฉ Docker Setup Compose แตยน
    runs-on: ubuntu-22.04
    environment: ${{ github.ref }}
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Step - Docker Setup Compose แตยน
        id: step_docker_setup-compose-action_v1
        uses: docker/setup-compose-action@v1
        with:
          version: ${{ inputs.version }} 
          cache-binary: ${{ inputs.cache-binary }}
