name: 'HashiCorp - Setup Terraform'
description: 'Sets up Terraform CLI in your GitHub Actions workflow.'

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID.'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key.'
        required: true
      WEBAPP_DB_MASTER_USERNAME:
        description: 'WebApp Database Master Username.'
        required: true
      WEBAPP_DB_MASTER_PASSWORD:
        description: 'WebApp Database Master Password.'
        required: true
    inputs:
      WEBAPP_DB_NAME:
        type: string
        description: 'WebApp Database Name.'
      cli_config_credentials_hostname:
        type: string
        default: 'app.terraform.io'
        description: 'Terraform Cloud/Enterprise hostname for CLI credentials.'
        required: false
      cli_config_credentials_token:
        type: string
        default: null
        description: 'API token for authenticating with Terraform Cloud/Enterprise.'
        required: false
      terraform_version:
        type: string
        default: 'latest'
        description: 'Terraform CLI version or constraint (e.g. `<1.13.0`). `latest` installs the newest version.'
        required: false
      terraform_wrapper:
        type: boolean
        default: true
        description: 'Install a wrapper to expose Terraform`s STDOUT, STDERR, and exit code as outputs.'
        required: false
jobs:
  job_hashicorp_setup-terraform_v2:
    name: 🧩 HashiCorp - Setup Terraform ᵛ²
    runs-on: ubuntu-22.04
    env:
      # Setting verbosity of Terraform logs.
      TF_LOG: ERROR
      # Setting AWS Access Key Id and Secret Access Key.
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Step - Checkout ᵛ³
        uses: actions/checkout@v3
        with:
          repository: '${{ github.repository }}'
          token: '${{ github.token }}'
      - name: Step - Setup Terraform ᵛ²
        id: step_hashicorp_setup-terraform_v2
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_hostname: ${{ inputs.cli_config_credentials_hostname }}
          cli_config_credentials_token: ${{ inputs.cli_config_credentials_token }}
          terraform_version: ${{ inputs.terraform_version }}
          terraform_wrapper: ${{ inputs.terraform_wrapper }}
